let  
    // 1. Récupérer une page JSON individuelle en utilisant RelativePath et les paramètres de requête   
    GetPage = (offset as number) as record =>  
        let  
            Source = Json.Document(  
                Web.Contents(  
                    "https://" & KoboServer,  
                    [  
                        RelativePath = "api/v2/assets/" & AssetUid & "/data.json",  
                        Query = [limit = Text.From(PageSize), offset = Text.From(offset)],  
                        Headers = [Authorization = "Token " & ApiToken]  
                    ]  
                )  
            )  
        in  
            Source,  
  
    // 2. Parcourir les pages de manière paginée en utilisant List.Generate  
    Pages = List.Generate(  
        () => [Result = GetPage(0), Offset = 0],  
        each [Offset] < [Result][count],  
        each [Result = GetPage([Offset] + PageSize), Offset = [Offset] + PageSize],  
        each [Result][results]  
    ),  
  
    // 3. Combiner les listes paginées en un seul résultat tabulaire  
    CombinedResults = List.Combine(Pages),  
    ResultsTable = Table.FromList(CombinedResults, Splitter.SplitByNothing(), null, null, ExtraValues.Error),  
  
    // 4. Extraire dynamiquement toutes les clés de champs uniques parmi toutes les soumissions  
    AllFieldNames = List.Distinct(List.Combine(List.Transform(CombinedResults, Record.FieldNames))),  
    ExpandedTable = Table.ExpandRecordColumn(ResultsTable, "Column1", AllFieldNames)  
in  
    ExpandedTable
